image: docker:20.10
services:
  - docker:20.10-dind

variables:
  DOCKER_TLS_CERTDIR: ""

stages:
  - test
  - build

before_script:
  - docker info

test_rust:
  stage: test
  image: rust:alpine3.21
  script:
    - apk add musl-dev
    - cargo --version
    - rustc --version
    - cargo clippy --fix --allow-dirty --all-targets
    - cargo test --all-features

build_docker_image:
  stage: build
  script:
    - docker build -t location-service:latest .
    - docker save location-service:latest | gzip > location-service.tar.gz # Это я просто вкинул сюда
  artifacts:
    paths:
      - location-service.tar.gz