image: docker:20.10
services:
  - docker:20.10-dind

variables:
  DOCKER_TLS_CERTDIR: ""

stages:
  - test
  - build



test_rust:
  stage: test
  image: rust:alpine3.21
  script:
    - apk add musl-dev
    - rustup component add clippy
    - rustup component add rustfmt
    - cargo clippy --all-targets --all-features --workspace
    - cargo fmt --check

build_docker_image:
  stage: build
  script:
    - docker build -t location-service:latest .
    - docker save location-service:latest | gzip > location-service.tar.gz # Это я просто вкинул сюда
  artifacts:
    paths:
      - location-service.tar.gz